version: 2
updates:
  - package-ecosystem: gradle
    directory: "/sample-api-client"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: "/sample-api-server"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
