services:

  pactbroker:
    image: pactfoundation/pact-broker:2.126.0-pactbroker2.113.0
    environment:
      PACT_BROKER_DATABASE_ADAPTER: sqlite
      PACT_BROKER_DATABASE_NAME: pactbroker
    ports:
      - "9292:9292"
