services:

  pactbroker:
    image: pactfoundation/pact-broker:2.107.0.1
    environment:
      PACT_BROKER_DATABASE_ADAPTER: sqlite
      PACT_BROKER_DATABASE_NAME: pactbroker
    ports:
      - "9292:9292"
