name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Start PactBroker
        run: docker compose up -d

      - name: Sample API Client check
        working-directory: sample-api-client
        run: ./gradlew check

      - name: Sample API Client Pact publish
        working-directory: sample-api-client
        run: ./gradlew pactPublish

      - name: Sample API Server check
        working-directory: sample-api-server
        run: ./gradlew check

      - name: Sample API Client can deploy?
        working-directory: sample-api-client
        run: ./gradlew canIDeploy

      - name: Sample API Server can deploy?
        working-directory: sample-api-server
        run: ./gradlew canIDeploy

      - name: Stop PactBroker
        run: docker compose down
