name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Gradle Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Start PactBroker
      run: docker compose up -d

    - name: Sample API Client check
      run: ./gradlew check
      working-directory: sample-api-client

    - name: Sample API Client Pact publish
      run: ./gradlew pactPublish
      working-directory: sample-api-client

    - name: Sample API Server check
      run: ./gradlew check
      working-directory: sample-api-server

    - name: Sample API Client can deploy?
      run: ./gradlew canIDeploy
      working-directory: sample-api-client

    - name: Sample API Server can deploy?
      run: ./gradlew canIDeploy
      working-directory: sample-api-server

    - name: Stop PactBroker
      run: docker compose down
