name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Java setup
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin

    - name: Start PactBroker
      run: docker compose up -d

    - name: Sample API Client check
      uses: gradle/actions/setup-gradle@v3
      with:
        build-root-directory: sample-api-client
        arguments: check

    - name: Sample API Client Pact publish
      uses: gradle/actions/setup-gradle@v3
      with:
        build-root-directory: sample-api-client
        arguments: pactPublish

    - name: Sample API Server check
      uses: gradle/actions/setup-gradle@v3
      with:
        build-root-directory: sample-api-server
        arguments: check

    - name: Sample API Client can deploy?
      uses: gradle/actions/setup-gradle@v3
      with:
        build-root-directory: sample-api-client
        arguments: canIDeploy

    - name: Sample API Server can deploy?
      uses: gradle/actions/setup-gradle@v3
      with:
        build-root-directory: sample-api-server
        arguments: canIDeploy

    - name: Stop PactBroker
      run: docker compose down
